name = "HasegawaWakatani"
uuid = "77b4a5b0-6ed9-4abb-b852-b72faee8deaf"
version = "0.12.0-DEV"
authors = ["JohannesMorkrid <johannes.e.morkrid@uit.no>"]

[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
H5Zblosc = "c8ec2601-a99c-407f-b158-e79c03c2f5f7"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
SMTPClient = "c35d69d1-b747-5018-a192-25bc5e63c83d"

[extensions]
HasegawaWakataniComponentArraysExt = "ComponentArrays"
HasegawaWakataniSMTPClientExt = "SMTPClient"

[compat]
Adapt = "4.4.0"
ComponentArrays = "0.15.29"
Documenter = "1"
FFTW = "1"
GPUArrays = ">=10"
H5Zblosc = "0.1"
HDF5 = "0.17"
Interpolations = ">= 0.15"
LaTeXStrings = "1"
MuladdMacro = "0.2"
Plots = "1"
ProgressMeter = "1"
SMTPClient = "0.6.4"
Statistics = "1.11.1"
Test = "1.11.0"
UnPack = "1"
julia = "1.8"

[extras]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
SMTPClient = "c35d69d1-b747-5018-a192-25bc5e63c83d"
