name = "HasegawaWakatani"
uuid = "77b4a5b0-6ed9-4abb-b852-b72faee8deaf"
authors = ["JohannesMorkrid <johannes.e.morkrid@uit.no>"]
version = "0.10.0-DEV"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
H5Zblosc = "c8ec2601-a99c-407f-b158-e79c03c2f5f7"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
SMTPClient = "c35d69d1-b747-5018-a192-25bc5e63c83d"

[extensions]
HasegawaWakataniComponentArraysExt = "ComponentArrays"
HasegawaWakataniSMTPClientExt = "SMTPClient"

[compat]
Adapt = "4.3.0"
CUDA = "5.6.1"
ComponentArrays = "0.15.29"
Dates = "1.11.0"
Plots = "1.40.9"
SMTPClient = "0.6.4"
